# Generated by Django 4.1.5 on 2023-02-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_intent",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
