# Generated by Django 4.1.5 on 2023-03-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_order_payment_intent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_intent",
            field=models.CharField(default="", max_length=255),
        ),
    ]
