# Generated by Django 4.1.5 on 2023-02-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_vendor",
            field=models.BooleanField(default=False),
        ),
    ]
